# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PULLMASI
email: i@pullmasi.com
description: > # this means to ignore newlines until "baseurl:"
  Join US, Just fork and write what you want then pull ma si.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pullmasi.com" # the base hostname & protocol for your site
twitter_username: pullmasi
github_username:  pullmasi

# Build settings
markdown: kramdown
